spring:
  application:
    name: book-inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_inventory
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:MC+Wos2SK728ig80cfHDRZBnhUdEfh+CaYWHjUrsKoQ=}
  expiration: 86400000 # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bookstore.bookinventory: DEBUG
    org.hibernate.SQL: DEBUG
