spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_users
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:MC+Wos2SK728ig80cfHDRZBnhUdEfh+CaYWHjUrsKoQ=}
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.bookstore.usermanagement: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

